### ISSUE TITLE
Query regarding image storage

### ISSUE THREAD

**Issue by jforjava1981** [rhsimplex/image-match#10]
Hi

 I intend to try out this project in my application however I have a doubt regarding the add image call. Does it actually store the image in elastic search server? I hope not. What I want to do is store the images elsewhere,possibly AWS S3 and use the URLs to add images though your app to elastic search and then search them whenever I want. If you store the images as well it is a double storage for my app. So just want to know.

**Comment by rhsimplex** [comment]
Hi @jforjava1981 , I see you already closed the issue but in case you are still wondering -- no, image-match does not store the images; it just stores the image signature and some additional information computed from the signature to aid in lookup.
