### ISSUE TITLE
How do I clear the image index so I can add another set of images?

### ISSUE THREAD

**Issue by bhavikshah1995** [rhsimplex/image-match#108]
I'd like to avoid redundancy of the same images appearing multiple times upon matching. Is there any way we can remove images, or completely empty the image index?

Edit:
As of now I'm having to use Curl to XDELETE the elasticsearch localhost, and load all images again, as this seems to be an elasticsearch related issue.
I'd still be glad if some functionality to remove images from index were introduced, or if they already do, be added to the documentation.

**Comment by taylorjdawson** [comment]
@bhavikshah1995 since you have the `elasticsearch` instance right in your code you can do this:
```
INDEX_NAME = 'images'
es = Elasticsearch()
es.indices.delete(INDEX_NAME)
```

See [this line](https://github.com/miqwit/image-match/blob/0b407287e90498b85f8d33b89ffe8a904b3a2c91/tests/test_elasticsearch_driver_speed.py#L97)

**Comment by bhavikshah1995** [comment]
@taylorjdawson That works well, thank you!
