### ISSUE TITLE
Completely fails to detect cropped versions of images added to index

### ISSUE THREAD

**Issue by bhavikshah1995** [rhsimplex/image-match#109]
I tried searching for cropped versions of images that were added to the index, but the results were completely off, such that the original image from which I had cropped the search image didn't even make it (even after extending distance_cutoff to 0.80). Is there any way we can work around this issue or is this a flaw in the algorithm itself that cannot be easily fixed?

**Comment by duhaime** [comment]
@bhavikshah1995 could you post some example images before and after the crop?

Could you also post the minimal code you're using to process your images?

I have identified hundreds of thousands of matching images that involve crops with image-match, but my data consisted mostly of line drawings.

**Comment by bhavikshah1995** [comment]
@duhaime 
Here are some examples in the order of uncropped image in the index and cropped image being searched:

![i0a2fd597128c11db9780000d60993453_uncropped](https://user-images.githubusercontent.com/46719531/53249125-01c4d700-367d-11e9-85a8-b1f1ff2d229e.png)
![gyrotonic_cropped](https://user-images.githubusercontent.com/46719531/53249144-0ab5a880-367d-11e9-94a9-7f5c97fbe583.png)

![i0a6da9427b6011dfbd20d521083c470e_uncropped](https://user-images.githubusercontent.com/46719531/53249423-a9420980-367d-11e9-8ae6-73546932bce8.png)
![smile_cropped](https://user-images.githubusercontent.com/46719531/53249432-ab0bcd00-367d-11e9-9497-ce64241d2a37.png)

![i6ea07216027711e4a60ae2600c90d6b4_uncropped](https://user-images.githubusercontent.com/46719531/53249535-e9a18780-367d-11e9-9e99-297fabfd12b8.png)
![greens_cropped](https://user-images.githubusercontent.com/46719531/53250111-5d905f80-367f-11e9-8d1c-ee96567e94d1.png)


![i7dd1f2c9b7e111df83eb9cce9d08ff46_uncropped](https://user-images.githubusercontent.com/46719531/53249643-3ab17b80-367e-11e9-9f6a-6517e5c0af8a.png)
![aad_cropped](https://user-images.githubusercontent.com/46719531/53249646-3c7b3f00-367e-11e9-979b-513ab8a9bdc1.png)


Here's the code I'm using to process the images:

    from elasticsearch import Elasticsearch
    from image_match.elasticsearch_driver import SignatureES
    es = Elasticsearch()
    ses = SignatureES(es, distance_cutoff = 0.50)

    import os
    files_path = 'C:\\Users\\UC244373\\Python_Images\\Sample_images\\'
    for filename in os.listdir(files_path):
        ses.add_image('C:\\Users\\UC244373\\Python_Images\\Sample_images\\'+filename)

    path = 'C:\\Users\\UC244373\\Pictures\\Screenshots\\Image Examples\\greens_cropped.png'
    ses.search_image(path, all_orientations=True)


Note that the images I have added to the index are of .mm file type, but I have tested the above for .png file types as well, with the same lack of result.

**Comment by rhsimplex** [comment]
I'm surprised the AAD example didn't work, but the others are simply to extreme for this algorithm.  You can try lowering the match thereshold, but I'm certain the other three examples will never work.

**Comment by bhavikshah1995** [comment]
@rhsimplex 
You mention in issue #40 that the algorithm is theoretically capable of heavy cropping. Is there any way you could shed some light on how one can go about implementing this?
