### ISSUE TITLE
Docker error

### ISSUE THREAD

**Issue by Clickbaitcake** [rhsimplex/image-match#110]
When pulling the Docker image I get the following errors:

`docker: Error response from daemon: pull access denied for ascribe/image-match, repository does not exist or may require 'docker login'.
`

**Comment by taylorjdawson** [comment]
The docker image doesn't exist but you can do this in the meantime:
```
docker build github.com/edjolabs/image-match.git
```

**Comment by rhsimplex** [comment]
Duplicates #13

**Comment by WathikAhmed** [comment]
Same issue.

`docker pull ascribe/image-match
Using default tag: latest
Error response from daemon: pull access denied for ascribe/image-match, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`

I can clone the repo, and then do this:
`docker build -t image-match.`

and it works to create the image:
<img width="538" alt="Screen Shot 2021-11-12 at 4 23 06 pm" src="https://user-images.githubusercontent.com/71957665/141414369-eeb8257f-c6db-4f2f-b36a-21a16cf1ac7b.png">

You can now try the following:
`docker pull wathik/image-match`

and then:
`docker run -it wathik/image-match /bin/bash`

Let me know if that works for you.
