### ISSUE TITLE
Docker image not found

### ISSUE THREAD

**Issue by sirioz** [rhsimplex/image-match#13]
I cannot pull docker image at ascribe/image-match. [not found]

**Comment by sbellem** [comment]
Yes sorry about this, we had some weird problem to link github and dockerhub for an automatic build.

I'll do my best to resolve this as soon as possible.

In the meantime if you clone this repo, you could build the image via the usual command, once in the image-match repo

``` bash
docker build -t image-match .
```

but I'll get back to asap

**Comment by rhsimplex** [comment]
@sbellem is this fixed?

**Comment by sbellem** [comment]
``` bash
$ docker pull ascribe/image-match
Using default tag: latest
latest: Pulling from ascribe/image-match

efd26ecc9548: Already exists 
a3ed95caeb02: Pull complete 
d1784d73276e: Already exists 
72e581645fc3: Already exists 
9709ddcc4d24: Already exists 
2d600f0ec235: Already exists 
de1491f1bbd4: Pull complete 
4becc568d2ff: Pull complete 
b507fa79b579: Pull complete 
cac748ede8ae: Pull complete 
6dca416256a4: Pull complete 
73e8a8ead95c: Pull complete 
e1e6faea08b5: Pull complete 
23079fda8772: Pull complete 
dc166976597d: Pull complete 
Digest: sha256:2fb7a9044d48ebcc2f37a09c93bd1cbe6305c13467da6384f40d07f166b281a1
Status: Downloaded newer image for ascribe/image-match:latest
```

**Comment by taylorjdawson** [comment]
I am unable to pull the docker file -- the issue may need to be reopened.

**Comment by Clickbaitcake** [comment]
Yes same here, please could you guys update the Docker repo?

**Comment by rhsimplex** [comment]
Yeah I see that it's gone, looks like ascribe organization has vanished.  @excerebrose I have requested access to set up the dockerhub link to this repository.  Then the references in the docs and `docker-compose.yml` will have to be changed.

**Comment by fanyoujian** [comment]
![image](https://user-images.githubusercontent.com/10875463/59414976-38258e00-8df5-11e9-8f63-9f73043b1d94.png)

**Comment by fanyoujian** [comment]
Error response from daemon: pull access denied for ascribe/image-match, repository does not exist or may require 'docker login'
, now  i try  docker build -t image-match .  , this ok?

**Comment by rhsimplex** [comment]
Looks like Ascribe has deleted their dockerhub repositories.  I have no control over that.  Maybe @ttmc can tell us what happened?

Anyway, the best solution is for @excerebrose to add this to a EdjoLabs repository and update the references.

**Comment by fanyoujian** [comment]
first  git clone https://github.com/EdjoLabs/image-match.git   or git clone https://github.com/ascribe/image-match.git


next : cd image-match


next: docker pull ascribe/image-match 


than err:
Error response from daemon: pull access denied for ascribe/image-match, repository does not exist or may require 'docker login'



so, next what i shoud do ?


------------------ 原始邮件 ------------------
发件人: "shiyuan"<notifications@github.com>;
发送时间: 2019年6月13日(星期四) 下午4:13
收件人: "EdjoLabs/image-match"<image-match@noreply.github.com>;
抄送: "慢半拍"<1620683945@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [EdjoLabs/image-match] Docker image not found (#13)




Looks like Ascribe has deleted their dockerhub repositories.  I have no control over that.  Maybe @ttmc can tell us what happened?
 
Anyway, the best solution is for @excerebrose to add this to a EdjoLabs repository and update the references.

**Comment by ttmc** [comment]
@rhsimplex is correct: ascribe (the Docker Hub organization) deleted all its repositories (in Docker Hub) and Docker images, so trying to do `docker pull ascribe/something` won't work any more.

The old ascribe/image-match GitHub repository was transferred to EdjoLabs so it has a new name: EdjoLabs/image-match, i.e. _this_ repository.

All the code is here. You don't need any Docker thingies or whatsits. Just git clone this repo then see [the README.md file](https://github.com/EdjoLabs/image-match/blob/master/README.md) and [the docs](https://image-match.readthedocs.io/en/latest/start.html) for help.

**Comment by fanyoujian** [comment]
I try this,but it no success; Can you give me the next steps in detail? thinks


------------------ 原始邮件 ------------------
发件人: "shiyuan"<notifications@github.com>;
发送时间: 2019年6月13日(星期四) 下午5:26
收件人: "EdjoLabs/image-match"<image-match@noreply.github.com>;
抄送: "慢半拍"<1620683945@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [EdjoLabs/image-match] Docker image not found (#13)




@rhsimplex is correct: ascribe (the Docker Hub organization) deleted all its repositories and Docker images, so trying to do docker pull ascribe/something won't work any more.
 
The old ascribe/image-match GitHub repository was transferred to EdjoLabs so it has a new name: EdjoLabs/image-match, i.e. this repository.
 
All the code is here. You don't need any Docker thingies or whatsits. Just git clone this repo then see the README.md file and the docs for help.

**Comment by ttmc** [comment]
@fanyoujian  I don't know what you tried or how it failed. If you can share _that_, then I might be able to help.

**Comment by fanyoujian** [comment]
next this my step:


1 python3.6.3. install




2 docker install




3 
	$ pip install numpy
	$ pip install scipy
	$ pip install image_match


	git clone https://github.com/ascribe/image-match.git


	cd  image-match


	$ pip install numpy
	$ pip install scipy
	$ pip install .


	docker pull ascribe/image-match


	last depart  this err :docker: Error response from daemon: pull access denied for ascribe/image-match, repository does not exist or may require 'docker login'.



please help me
------------------ 原始邮件 ------------------
发件人: "shiyuan"<notifications@github.com>;
发送时间: 2019年6月13日(星期四) 晚上7:38
收件人: "EdjoLabs/image-match"<image-match@noreply.github.com>;
抄送: "慢半拍"<1620683945@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [EdjoLabs/image-match] Docker image not found (#13)




@fanyoujian  I don't know what you tried or how it failed. If you can share that, then I might be able to help.

**Comment by ttmc** [comment]
As noted above, you don't need to do any Docker anything. Try this (and only this):

```text
git clone https://github.com/ascribe/image-match.git
cd  image-match
python --version
# Hopefully it says Python 3.something, if not, create a Python 3.6 virtualenv and activate it
pip install numpy
pip install scipy
pip install .
```
and if that fails then please copy and paste the error messages here.

**Comment by fanyoujian** [comment]
#demo.py

from elasticsearch import Elasticsearch
from image_match.elasticsearch_driver import SignatureES

es = Elasticsearch('http://localhost:9200')
ses = SignatureES(es)

ses.add_image('http://images-new.123rf.com.cn/450wm/grycikua/grycikua1610/grycikua161000013.jpg')

when i run python demo.py err:

raise ConnectionTimeout('TIMEOUT', str(e), e)
elasticsearch.exceptions.ConnectionTimeout: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='localhost', port=9200): Read timed out. (read timeout=10))







my local elasticsearch version2.2.1





------------------ 原始邮件 ------------------
发件人: "shiyuan"<notifications@github.com>;
发送时间: 2019年6月13日(星期四) 晚上10:53
收件人: "EdjoLabs/image-match"<image-match@noreply.github.com>;
抄送: "慢半拍"<1620683945@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [EdjoLabs/image-match] Docker image not found (#13)




As noted above, you don't need to do any Docker anything. Try this (and only this):
 git clone https://github.com/ascribe/image-match.git cd  image-match python --version # Hopefully it says Python 3.something, if not, create a Python 3.6 virtualenv and activate it pip install numpy pip install scipy pip install .  
and if that fails then please copy and paste the error messages here.

**Comment by ttmc** [comment]
@fanyoujian Is Elasticsearch running on your system (and healthy)? One way to check is to do this on the command line:

```bash
curl localhost:9200/
```

**Comment by fanyoujian** [comment]
Hello,thinks for you help;
Can't I search the detailed graph directly? but i find now it can't image_match search for similar images at present? Must I upload to es before I can search? 


------------------ 原始邮件 ------------------
发件人: "shiyuan"<notifications@github.com>;
发送时间: 2019年6月13日(星期四) 晚上10:53
收件人: "EdjoLabs/image-match"<image-match@noreply.github.com>;
抄送: "慢半拍"<1620683945@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [EdjoLabs/image-match] Docker image not found (#13)




As noted above, you don't need to do any Docker anything. Try this (and only this):
 git clone https://github.com/ascribe/image-match.git cd  image-match python --version # Hopefully it says Python 3.something, if not, create a Python 3.6 virtualenv and activate it pip install numpy pip install scipy pip install .  
and if that fails then please copy and paste the error messages here.

**Comment by ttmc** [comment]
The information about an image must be in Elasticsearch or you'll never find it there.

If you want to search the whole World Wide Web for similar images, then try:

- https://images.google.com/
- https://tineye.com/

**Comment by WathikAhmed** [comment]
Same issue.

`docker pull ascribe/image-match
Using default tag: latest
Error response from daemon: pull access denied for ascribe/image-match, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`

I can clone the repo, and then do this:
`docker build -t image-match.`

and it works to create the image:
<img width="538" alt="Screen Shot 2021-11-12 at 4 23 06 pm" src="https://user-images.githubusercontent.com/71957665/141414369-eeb8257f-c6db-4f2f-b36a-21a16cf1ac7b.png">

You can now try the following:
`docker pull wathik/image-match`

and then:
`docker run -it wathik/image-match /bin/bash`

Let me know if that works for you.
