### ISSUE TITLE
about ext data

### ISSUE THREAD

**Issue by smallevil** [rhsimplex/image-match#17]
Hi
This project is great, thank you for your open source.
In use, I feel a little less convenient.
When used in conjunction with the ES, add_image ext data can add a field, json format
such as:
add_image ( 'image url', 'json data')
Back out in the search results come together.

Thus, when adding pictures, you can write the image with some extra information, search can directly get.

Own little experience.
We are hoping to add this feature.
Thank you

**Comment by rhsimplex** [comment]
@smallevil excellent idea, and not that difficult to implement.  Hopefully I'll have some time to do that in the near future, but in the meantime if you manage to make the change please do send us a PR!

**Comment by rhsimplex** [comment]
Resloved by #26
