### ISSUE TITLE
Add integration tests

### ISSUE THREAD

**Issue by vrde** [rhsimplex/image-match#18]
To improve development speed and PRs review we can add some integration tests.

We can test `image-match` as a "blackbox", having a directory with images on one side, and expected fingerprints on the other. We can always work on unit tests later.

**Comment by sbellem** [comment]
docker!!!!

**Comment by sbellem** [comment]
we can use the [docker-compose.yml](https://github.com/ascribe/image-match/blob/master/docker-compose.yml)

**Comment by rhsimplex** [comment]
@vrde @sbellem See https://github.com/ascribe/image-match/tree/integration_tests

Right now works just like http://bigchaindb.readthedocs.org/en/develop/running-unit-tests.html including the Docker support =)

Will add more tests over the coming week(s).

**Comment by sbellem** [comment]
:+1:

**Comment by rhsimplex** [comment]
Resolved with #19
