### ISSUE TITLE
Why "An image signature for any kind of image, Wong et al" instead of pHash?

### ISSUE THREAD

**Issue by mladdict** [rhsimplex/image-match#20]
Thanks for the awesome package. Is there a rationale for choosing to implement the digital signature from "An image signature for any kind of image, Wong et al" versus pHash?

**Comment by rhsimplex** [comment]
Glad you find it helpful.  To answer your question: part of it was ignorance of the field, and part of it was licensing.  

To the first part, we looked into pHash, but I didn't understand how to make it scale to 1B+ images at the time.  The Wong paper addresses that. Of course, now I see that the database method of storing the signatures could work for any hashing library, including pHash.

As for licensing, we weren't sure how we were going to distribute image-match and the pHash library uses [GPL 3](http://www.phash.org/licensing/), which was a little too restrictive. 

I would be really nice if we had plugins for other hashing libraries, certainly.
