### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by rhsimplex** [rhsimplex/image-match#27]
Added some new features, @sbellem will need a little help from you =)

**Comment by kingroryg** [comment]
I'm free . :p I'd like to contribute to this 👍

**Comment by rhsimplex** [comment]
@saru95 this is pretty much done, I forgot to close the issue. If you want to work on something a little more complex, maybe #2 ? If so, go reply to the issue and I'll spell out in detail what needs to be done.
