### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by rhsimplex** [rhsimplex/image-match#3]
Join the future of Python

**Comment by kingroryg** [comment]
We are looking at both py2 and py3 compatibility here or are we looking to totally port it to py3 ?

**Comment by rhsimplex** [comment]
Looking to move to Python3 eventually -- don't really have the bandwidth to support parallel releases. I'm working on some integration tests #19 first, which should help ease the transition.

**Comment by rr-** [comment]
Are the tests finished? Can I work on the port?

**Comment by rhsimplex** [comment]
Yes, tests covering the important functionality are written and merged.  You can run them with `py.test`. I'll probably add more soon.

@rr- I'd be thrilled if you work on porting this to python3 and of course I will help when I can.

**Comment by kingroryg** [comment]
👍

**Comment by rhsimplex** [comment]
Solved by #30, thank you @saru95

**Comment by rr-** [comment]
Very cool! (Sorry for the delay.) I think the version should be bumped, trying to upgrade it with `python3 setup.py install` says the version is already at 0.3 - had to reinstall it manually. Plus it's a good idea to setup the PIP package for Py3, or bump it (not sure if it boils down to the same thing as the first proposition).

**Comment by rhsimplex** [comment]
@rr- yes definitely, I will bump the version and set it up on pypi tomorrow

**Comment by rhsimplex** [comment]
@rr- this is done. Can you verify `pip install` is working?

**Comment by rr-** [comment]
Yep, it works. Thank you.
