### ISSUE TITLE
Storing and Searching

### ISSUE THREAD

**Issue by Lvctao** [rhsimplex/image-match#38]
This is the example in quick start, a TypeError "**_TypeError: unorderable types: dict() > dict()_**" occured when I run it. Have you ever encountered this problem?

**The code is:**

`from elasticsearch import Elasticsearch
from image_match.elasticsearch_driver import SignatureES

es = Elasticsearch()
ses = SignatureES(es)

ses.add_image('https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Mona_Lisa,_by_Leonardo_da_Vinci,_from_C2RMF_retouched.jpg/687px-Mona_Lisa,_by_Leonardo_da_Vinci,_from_C2RMF_retouched.jpg')

ses.add_image('https://pixabay.com/static/uploads/photo/2012/11/28/08/56/mona-lisa-67506_960_720.jpg')

ses.add_image('https://upload.wikimedia.org/wikipedia/commons/e/e0/Caravaggio_-_Cena_in_Emmaus.jpg')

ses.add_image('https://c2.staticflickr.com/8/7158/6814444991_08d82de57e_z.jpg')

list = ses.search_image('https://pixabay.com/static/uploads/photo/2012/11/28/08/56/mona-lisa-67506_960_720.jpg')

print(list)`

When it was excuted, "**_TypeError: unorderable types: dict() > dict()_**" occurred. The detailed problem is as follows.
`runfile('/Users/lvchangtao/local-image-match/storeSearching.py', wdir='/Users/lvchangtao/local-image-match')

/Users/lvchangtao/anaconda3/lib/python3.5/site-packages/image_match/goldberg.py:402: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future

lower_y_lim:upper_y_lim]) # no smoothing here as in the paper

Traceback (most recent call last):

File "", line 1, in

File "/Users/lvchangtao/anaconda3/lib/python3.5/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 714, in runfile
execfile(filename, namespace)

File "/Users/lvchangtao/anaconda3/lib/python3.5/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 89, in execfile
exec(compile(f.read(), filename, 'exec'), namespace)

File "/Users/lvchangtao/local-image-match/storeSearching.py", line 20, in 
list = ses.search_image('https://pixabay.com/static/uploads/photo/2012/11/28/08/56/mona-lisa-67506_960_720.jpg')

File "/Users/lvchangtao/anaconda3/lib/python3.5/site-packages/image_match/signature_database_base.py", line 270, in search_image
r = sorted(np.unique(result).tolist(), key=itemgetter('dist'))

File "/Users/lvchangtao/anaconda3/lib/python3.5/site-packages/numpy/lib/arraysetops.py", line 198, in unique
ar.sort()

TypeError: unorderable types: dict() > dict()`

**Comment by Lvctao** [comment]
I have figure out the problem. It is a BUG in _numpy-1.11.1_. The factor is that in Python 3.x `list.sort()` no longer accept the `cmp` argument providing a comparison function. It should use the `Key` argument instead of `ar.sort()`.
The reference documentation site is "_https://docs.python.org/3/whatsnew/3.0.html#ordering-comparisons_"

**Comment by rhsimplex** [comment]
Hi @Lvctao, I was able to reproduce this, thanks for finding it.  I'll try to fix it today.

**Comment by rhsimplex** [comment]
Fixed, and the new version is on Pypi. Thanks again @Lvctao

**Comment by Lvctao** [comment]
My solution is delete "ar.sort()"  in line 198 in arraysetops.py. I know this solution  isincorrect. Could you tell me why the problem occurred or how to fix it. 

发自 网易邮箱大师
On 08/19/2016 17:52, Ryan Henderson wrote:

Fixed, and the new version is on Pypi. Thanks again @Lvctao

**Comment by rhsimplex** [comment]
If you do `pip install image_match --upgrade` that should fix the issue.  The problem was `set` and `np.unique` could work on dictionaries in python2 but not python3.  @vrde fixed it by checking the `id` of each image directly.  We also added a new test so this doesn't happen again.
