### ISSUE TITLE
Hi, I havent installed it yet but can this search find two .............

### ISSUE THREAD

**Issue by imerkle** [rhsimplex/image-match#56]
Hi, I havent installed it yet but can this search find two images of same person in completely different settings for example

[OBAMA 1](https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcThzH4YQ6Thbx5rFHB3xZLB_s_4rJvKm6r0XHrcs-4_9PlE3bXx)

And [OBAMA 2](https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTyzOSF0tUckQkD5hEtnP_pJnGAxufETaGZHdyQRmrEQ2MQ2KOuUQ)

**Comment by rhsimplex** [comment]
Sorry for the late reply.  No, this is not an object detection engine.  It's for finding slightly modified versions of the _same image_.
