### ISSUE TITLE
Python 3.5 issue with compute_mean_level method in ImageSignature

### ISSUE THREAD

**Issue by eggytronixx** [rhsimplex/image-match#57]
`
avg_grey[i, j] = np.mean(image[lower_x_lim:upper_x_lim,
                                        lower_y_lim:upper_y_lim])  # no smoothing here as in the paper
`

lower_x_lim, upper_x_lim, lower_y_lim, and upper_y_lim are causing the slice to through an exception in python 3.5.

Does anyone else have this issue?

**Comment by rhsimplex** [comment]
Could you share the image causing the issue?

**Comment by kern** [comment]
Error I'm seeing is `TypeError: slice indices must be integers or None or have an __index__ method`

**Comment by eggytronixx** [comment]
I believe it was a type error. I did the following to the source, and it fixed the issue. 
The values for lower_x_lim, upper_x_lim, lower_y_lim, and upper_y_lim should be int not float

@rhsimplex I would using the url from the demo example on the docs page

![screen shot 2017-01-26 at 8 31 32 pm](https://cloud.githubusercontent.com/assets/4821893/22360643/a5afc7e2-e406-11e6-90f2-dccd79bd3c9d.png)

**Comment by rhsimplex** [comment]
@eggytronixx hey thanks for the fix.  I'm traveling until next week, then I can fix it. Alternatively, you can make a PR and I'll merge it immediately if the tests pass 😁

**Comment by rhsimplex** [comment]
Closed by #58 Thanks @eggytronixx :+1:

**Comment by eggytronixx** [comment]
@rhsimplex 👍🏾
