### ISSUE TITLE
Feature request: make cairosvg optional

### ISSUE THREAD

**Issue by rr-** [rhsimplex/image-match#59]
It's pretty big dependency; I think many people would be happy with PIL / Pillow alone.

**Comment by rhsimplex** [comment]
Agree, we added it due to a business need at the time but it's generally useless.  I don't work on this codebase much anymore but would be thrilled to merge if you make a PR

**Comment by rr-** [comment]
Roger

**Comment by rhsimplex** [comment]
Closed by #61, thanks again
