### ISSUE TITLE
Skip duplicates on indexing? 

### ISSUE THREAD

**Issue by ecdeveloper** [rhsimplex/image-match#69]
Is there a way to skip indexing an image, if it already has been indexed? I have some images in elasticsearch, and I need to index some others. However, some of those images were already indexed. Is there way to make those images, which have 100% match in DB, to not be indexed again?

**Comment by rhsimplex** [comment]
Currently, no.  You could do a lookup first and only accept new images above a certain distance, but this would add a lot of overhead to the image insertion and therefore could not be a default configuration.  

Alternatively, if the filenames (or something) are unique, you could index on that with Elasticsearch.
