### ISSUE TITLE
cannot resize an array that references

### ISSUE THREAD

**Issue by sctrueew** [rhsimplex/image-match#80]
hi ...
when i wanna call ses.add_image i got this error : 

ses.add_image('https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Mona_Lisa,_by_Leonardo_da_Vinci,_from_C2RMF_retouched.jpg/687px-Mona_Lisa,_by_Leonardo_da_Vinci,_from_C2RMF_retouched.jpg')

my error : 
cannot resize an array that references or is referenced

by another array in this way.  Use the resize function

**Comment by sctrueew** [comment]
solved :)

**Comment by TRINHHOANGANH** [comment]
@sctrueew Can you share how you solved this error?
