### ISSUE TITLE
Find Sub images in larger image

### ISSUE THREAD

**Issue by janetthecoder** [rhsimplex/image-match#87]
Is it possible to use this to find sub images in larger images?

So for instance if I have a picture of 20 books arranged neatly, and want to find 1 of those books, can this be used, and can we return a bounded box for that image?

**Comment by duhaime** [comment]
@janetthecoder I think this image has some discussion here: https://github.com/ascribe/image-match/issues/40

If you agree that this issue is a dupe of #40, it might make sense to close this issue to concentrate conversation in that other thread...

**Comment by janetthecoder** [comment]
Agreed
