### ISSUE TITLE
Expose a method for setting user-agents in ImageSigntaure().generate_signature().

### ISSUE THREAD

**Issue by Hyperclaw79** [rhsimplex/image-match#95]
Since the underlying functions use `Urllib` to fetch the images from external links, I am stumbling upon `403 error`s. It would be helpful if I could set custom headers to bypass this problem.

I can easily access the same links with `Requests` module.

The [example link](https://cdn.discordapp.com/attachments/408321293960871956/456783325995073577/PokecordSpawn.jpg).

**Comment by excerebrose** [comment]
Hey @Hyperclaw79 Sorry for the late reply, at the moment the URL handling is done by skimage.io.imread, you can use the the bytestream option to predownload them image and then generate the signature
```
r = requests.get('<url>', headers={'user-agent': '<your string>})
if r.status_code == 200:
      sig = ImageSignature().generate_signature(r.content, bytestream=True)
```

**Comment by Hyperclaw79** [comment]
Thanks, I'll give it a try.
