### ISSUE TITLE
why you don't add numpy and scipy in image-match's dependencies

### ISSUE THREAD

**Issue by GreatBahram** [rhsimplex/image-match#99]
Hi
First of all thanks for you project. I was wonder why you didn't add numpy and scipy to your `install_requires` in `setup.py`? I wanted to add them but I did not what version you have used.

**Comment by duhaime** [comment]
@GreatBahram Thanks for your note. Both numpy and scipy *should* be pulled in via the scikit-image dependency, which lists both modules in its `install_requires` [[link](https://github.com/scikit-image/scikit-image)]. Are they not being installed upon install of scikit-image on your host?

Do you think numpy and scipy should be treated differently in the context of image-match? If so I'm curious to hear your thoughts...

**Comment by GreatBahram** [comment]
@duhaime well I have checked the link you mention it. And your are right. I have no idea why when I tried to install `image-match` it showed an error about numpy and scipy. No need to add them in `image-match` since it just add more functionality in `scikit-image` and you guys don't care about which numpy and scipy version gonna install on user computer.
Thanks
